### ISSUE TITLE
Can't Delete a User.

### ISSUE THREAD

**Issue by Vamshi-Kalleboina** [CarlomagnoLopez/php-medical-app#103]
Created an Organization with 2 Org Admin, 2 Approvers, 2 Users were added but can't delete a user.
The Delete option is not responding or any pop up is being shown as a message.

![Screenshot (32)](https://user-images.githubusercontent.com/65308703/94598692-510db900-025d-11eb-84e6-c34daf022ddb.png)

**Comment by chandupoloju** [comment]
All roles of users can be deleted..
Minimum 2 Org Admins mandatory
Minimum 2 Approvers mandatory
