### ISSUE TITLE
Unable to enter into group which was created by himself/herself

### ISSUE THREAD

**Issue by chandupoloju** [CarlomagnoLopez/php-medical-app#12]
I created a test group in application with password, other than me other users can enter that group with using that password. But Im unable to enter it. Showing as banned..

**Comment by chandupoloju** [comment]
![Screenshot (248)](https://user-images.githubusercontent.com/47585687/88079315-2804e400-cb9b-11ea-922b-05080118d28d.png)
**Here on right top, you can see BANNED banner..**

**Comment by CarlomagnoLopez** [comment]
Hi Chandu, we solve that problem, can you test again?
