### ISSUE TITLE
Clicking on menu should close the menu, but it staying still and menu not closing

### ISSUE THREAD

**Issue by chandupoloju** [CarlomagnoLopez/php-medical-app#123]

**Comment by jayanthallumalla** [comment]
which menu? what is that menu option you're talking about?? @chandupoloju

**Comment by chandupoloju** [comment]
![Screenshot_2020-10-10-23-13-23-873_com android chrome](https://user-images.githubusercontent.com/47585687/95661865-713c5280-0b50-11eb-95e4-1acf8335f05a.jpg)
