### ISSUE TITLE
Any user can edit other users details

### ISSUE THREAD

**Issue by chandupoloju** [CarlomagnoLopez/php-medical-app#13]
![Screenshot (249)](https://user-images.githubusercontent.com/47585687/88079567-84680380-cb9b-11ea-8997-db3cfc061afa.png)

**Comment by CarlomagnoLopez** [comment]
This one is because you are an org admin, this role can edit the user,  but we should fit the form to the correct fields, so the fields we need to show there are the same fields that the singup form.
