### ISSUE TITLE
unable to open files from files section

### ISSUE THREAD

**Issue by chandupoloju** [CarlomagnoLopez/php-medical-app#46]
![Screenshot (298)](https://user-images.githubusercontent.com/47585687/90418510-d3d61c80-e0d2-11ea-936e-0a948e4b5b8a.png)

**Comment by darmando** [comment]
Hi @chandupoloju  What type of file did you try open?

**Comment by chandupoloju** [comment]
we shared some files in groups images. We are seeing them as null in files section and unable to open

**Comment by darmando** [comment]
oh! yea, I found the error,  I'm fixing it
