### ISSUE TITLE
Organization is not being deleted

### ISSUE THREAD

**Issue by Vamshi-Kalleboina** [CarlomagnoLopez/php-medical-app#52]
The created organization is not getting deleted, pops up an error as shown below.

![Screenshot (211)](https://user-images.githubusercontent.com/65308703/90674778-9a62f580-e227-11ea-94fb-e3926d91e773.png)

**Comment by jayanthallumalla** [comment]
The organization will be deleted only after deleting all the users in it .
only 2 org admins and 2 approvers should be there to delete the organization. All the other users should be deleted manually
