### ISSUE TITLE
Can share any type of file but can view only .jpg format files.

### ISSUE THREAD

**Issue by Vamshi-Kalleboina** [CarlomagnoLopez/php-medical-app#59]
In chat, we can share all the format of files but can open and view only .jpg format files. 
Rest any type of file keeps loading but not at all opening. Tried this from the shared file from a contact in chat/group chat.
From Files in Left side pane, it's not even responding for view option. 

![Screenshot (218)](https://user-images.githubusercontent.com/65308703/90924888-4cccc100-e3be-11ea-874f-a6f522e9675c.png)
![Screenshot (217)](https://user-images.githubusercontent.com/65308703/90924892-4f2f1b00-e3be-11ea-82b1-377e26e3a8b7.png)

**Comment by jayanthallumalla** [comment]
It is done
