### ISSUE TITLE
The Roles are getting reversed

### ISSUE THREAD

**Issue by Vamshi-Kalleboina** [CarlomagnoLopez/php-medical-app#67]
I have created an Organization and assigned roles making me as an Admin and Laxmikanth as Admin 2 and Chandu and Sai Kiran as Approvers but when the Users list is seen with reverse roles as me and Laxmikanth as Approvers and rest as Org. Admins.

![Screenshot (4)](https://user-images.githubusercontent.com/65308703/93229708-dd3fbc80-f744-11ea-8db8-084becc02cf2.png)

**Comment by jayanthallumalla** [comment]
Its done
