### ISSUE TITLE
New Users cannot be added into the Existing Organization

### ISSUE THREAD

**Issue by Vamshi-Kalleboina** [CarlomagnoLopez/php-medical-app#69]
Error while trying to add new users into the existing organization. The Company Name is given still not accepting it. 

![Screenshot (5)](https://user-images.githubusercontent.com/65308703/93232707-32c99880-f748-11ea-9846-06bc347e47ff.png)

**Comment by jayanthallumalla** [comment]
duplicate issue - and its solved
