### ISSUE TITLE
The Files shared can be viewed only from Group, but cannot be viewed from the Files

### ISSUE THREAD

**Issue by Vamshi-Kalleboina** [CarlomagnoLopez/php-medical-app#73]
The files shared can only be viewed from the Group chat or the User chat but failed to open to view from the  Files options in the Dashboard. It is showing an option as loading and not working or the image is opened.

![Screenshot (7)](https://user-images.githubusercontent.com/65308703/93249112-cc03a980-f75e-11ea-91c3-7d496e8007a8.png)

**Comment by jayanthallumalla** [comment]
It should be like this only
