### ISSUE TITLE
 In Medical Chat group, Invite with phone number was not working. 

### ISSUE THREAD

**Issue by Vamshi-Kalleboina** [CarlomagnoLopez/php-medical-app#75]
In an organization group, we can invite external users to that group by phone number. 
If the user doesn’t exist in the system, they will invite through phone number right. But that is not working to add a new user into the group via phone number.

The Phone is valid and which is being used, no issue with the number.

![Screenshot (9)](https://user-images.githubusercontent.com/65308703/93258523-6c13ff80-f76c-11ea-81ca-089657e060e6.png)
.

**Comment by jayanthallumalla** [comment]
Invite function is working now, but the functionality is, we can invite users only who are already registered in the group(it's old functionality may be)
